import XCTest
@testable import VaultCrypto
@testable import VaultCore

/// Runs the vector corpus produced by sealstone-format against this
/// implementation.
///
/// The corpus was generated by the Python reference decoder, which shares no
/// code with this. Agreement between the two is the actual evidence that the
/// format is implemented correctly rather than merely implemented twice.
final class ConformanceTests: XCTestCase {
    private var vectors: URL {
        guard let url = Bundle.module.url(forResource: "Vectors", withExtension: nil) else {
            fatalError("the vector corpus is missing — run Scripts/sync-vectors.sh")
        }
        return url
    }

    private var manifest: [String: Any] {
        let data = try! Data(contentsOf: vectors.appendingPathComponent("manifest.json"))
        return try! JSONSerialization.jsonObject(with: data) as! [String: Any]
    }

    private var families: [[String: Any]] {
        manifest["families"] as! [[String: Any]]
    }

    private func families(ofKind kind: String) -> [[String: Any]] {
        families.filter { $0["kind"] as? String == kind }
    }

    private func bytes(_ relativePath: String) throws -> [UInt8] {
        try [UInt8](Data(contentsOf: vectors.appendingPathComponent(relativePath)))
    }

    private func passphrase(_ entry: [String: Any], key: String = "passphraseUtf8Hex") -> String {
        let hex = entry[key] as! String
        var bytes = [UInt8]()
        var index = hex.startIndex
        while index < hex.endIndex {
            let next = hex.index(index, offsetBy: 2)
            bytes.append(UInt8(hex[index..<next], radix: 16)!)
            index = next
        }
        return String(decoding: bytes, as: UTF8.self)
    }

    private var runSlow: Bool {
        ProcessInfo.processInfo.environment["SEALSTONE_SLOW_TESTS"] == "1"
    }

    // MARK: - Corpus integrity

    func testCorpusIsPresentAndCurrent() {
        XCTAssertEqual(manifest["formatVersion"] as? Int, 1)
        XCTAssertGreaterThanOrEqual(families.count, 9,
            "the corpus looks incomplete — run Scripts/sync-vectors.sh")
    }

    // MARK: - Files that must open

    func testFilesThatMustOpenDoOpen() throws {
        for family in families(ofKind: "open-succeeds") {
            let id = family["id"] as! String
            if family["slow"] as? Bool == true, !runSlow { continue }

            let blob = try bytes(family["file"] as! String)
            let expected = try bytes(family["expectedPlaintext"] as! String)

            let (plaintext, header) = try Impression.open(
                blob, using: .passphrase(passphrase(family)))

            XCTAssertEqual(plaintext, expected, "\(id): plaintext differs")

            let declared = family["expectedHeader"] as! [String: Any]
            XCTAssertEqual(Int(header.formatMajor), declared["formatMajor"] as? Int, id)
            XCTAssertEqual(Int(header.kdf.rawValue), declared["kdfId"] as? Int, id)
            XCTAssertEqual(Int(header.aead.rawValue), declared["aeadId"] as? Int, id)
            XCTAssertEqual(header.memoryKiB, declared["kdfMemoryKiB"] as? Int, id)
            XCTAssertEqual(header.iterations, declared["kdfIterations"] as? Int, id)
            XCTAssertEqual(header.parallelism, declared["kdfParallelism"] as? Int, id)

            // The plaintext must also decode as a vault document.
            _ = try JSONDecoder().decode(VaultDocument.self, from: Data(plaintext))
        }
    }

    func testNormalisationEquivalentPassphrasesAllOpen() throws {
        for family in families(ofKind: "open-succeeds") {
            guard let spellings = family["equivalentPassphrasesUtf8Hex"] as? [String] else {
                continue
            }
            let blob = try bytes(family["file"] as! String)
            let expected = try bytes(family["expectedPlaintext"] as! String)

            for spelling in spellings {
                let text = passphrase(["p": spelling], key: "p")
                let (plaintext, _) = try Impression.open(blob, using: .passphrase(text))
                XCTAssertEqual(plaintext, expected,
                    "\(family["id"] as! String): a normalisation-equivalent passphrase failed")
            }
        }
    }

    func testUnknownItemTypeSurvivesRoundTrip() throws {
        let family = families(ofKind: "open-succeeds").first { $0["id"] as? String == "03-full-vault" }!
        let blob = try bytes(family["file"] as! String)
        let (plaintext, _) = try Impression.open(blob, using: .passphrase(passphrase(family)))

        let document = try JSONDecoder().decode(VaultDocument.self, from: Data(plaintext))
        let future = document.items.filter { !$0.payload.isUnderstood }
        XCTAssertEqual(future.count, 1, "the unknown item type was dropped")
        XCTAssertEqual(future.first?.payload.typeName, "typeFromTheFuture")

        // Re-encoding must not lose it.
        let reencoded = try JSONEncoder().encode(document)
        let again = try JSONDecoder().decode(VaultDocument.self, from: reencoded)
        XCTAssertEqual(again.items.filter { !$0.payload.isUnderstood }.count, 1,
                       "the unknown item type was lost on re-encoding")
    }

    // MARK: - Files that must not open

    func testEveryTamperedRegionIsRejected() throws {
        let family = families(ofKind: "open-fails").first { $0["id"] as? String == "05-tamper" }!
        let text = passphrase(family)

        // The untampered original must open, or the family proves nothing.
        _ = try Impression.open(try bytes(family["original"] as! String),
                                using: .passphrase(text))

        for testCase in family["cases"] as! [[String: Any]] {
            let region = testCase["region"] as! String
            let blob = try bytes(testCase["file"] as! String)

            XCTAssertThrowsError(try Impression.open(blob, using: .passphrase(text)),
                                 "a file tampered in the \(region) region was accepted") { error in
                XCTAssertTrue(error is ImpressionError,
                              "\(region) failed with \(error), not a format error")
            }
        }
    }

    /// Truncation is a different failure from tampering: the surviving bytes
    /// are genuine, so an implementation that reads before checking length
    /// crashes rather than reporting.
    func testEveryTruncationIsRejectedCleanly() throws {
        guard let family = families(ofKind: "open-fails").first(where: {
            $0["id"] as? String == "11-truncation"
        }) else {
            return XCTFail("the truncation family is missing — run Scripts/sync-vectors.sh")
        }
        let text = passphrase(family)

        _ = try Impression.open(try bytes(family["original"] as! String),
                                using: .passphrase(text))

        for testCase in family["cases"] as! [[String: Any]] {
            let name = testCase["name"] as! String
            let blob = try bytes(testCase["file"] as! String)

            XCTAssertThrowsError(try Impression.open(blob, using: .passphrase(text)),
                                 "truncation '\(name)' was accepted") { error in
                XCTAssertTrue(error is ImpressionError,
                              "truncation '\(name)' failed with \(error)")
            }
        }
    }

    func testWrongPassphrasesAreRejected() throws {
        let family = families(ofKind: "open-fails").first { $0["id"] as? String == "06-wrong-passphrase" }!
        let blob = try bytes(family["file"] as! String)

        for testCase in family["cases"] as! [[String: Any]] {
            let reason = testCase["reason"] as! String
            XCTAssertThrowsError(
                try Impression.open(blob, using: .passphrase(passphrase(testCase))),
                "accepted a file it should not have: \(reason)")
        }
    }

    func testHostileParametersAreRefusedBeforeAllocation() throws {
        for family in families(ofKind: "reject-before-allocation") {
            let text = passphrase(family)
            for testCase in family["cases"] as! [[String: Any]] {
                let name = testCase["name"] as! String
                let blob = try bytes(testCase["file"] as! String)

                XCTAssertThrowsError(try Impression.open(blob, using: .passphrase(text)),
                                     "hostile parameters accepted: \(name)") { error in
                    // Must be caught by a range check, not by a failed
                    // derivation or by the process being killed.
                    guard case ImpressionError.parametersOutOfRange = error else {
                        return XCTFail("\(name) failed with \(error), not a range check")
                    }
                }
            }
        }
    }

    func testDeclaredLimitsMatchTheImplementation() throws {
        let family = families(ofKind: "reject-before-allocation").first!
        let limits = family["limits"] as! [String: Any]

        func maximum(_ key: String) -> Int {
            (limits[key] as! [String: Any])["max"] as! Int
        }
        XCTAssertEqual(maximum("kdfMemoryKiB"), Impression.maxMemoryKiB)
        XCTAssertEqual(maximum("kdfIterations"), Impression.maxIterations)
        XCTAssertEqual(maximum("kdfParallelism"), Impression.maxParallelism)
    }

    // MARK: - Shamir

    func testShamirVectors() throws {
        for family in families(ofKind: "shamir") {
            let secretHex = family["secretHex"] as! String
            var secret = [UInt8]()
            var index = secretHex.startIndex
            while index < secretHex.endIndex {
                let next = secretHex.index(index, offsetBy: 2)
                secret.append(UInt8(secretHex[index..<next], radix: 16)!)
                index = next
            }

            var shares = [Int: Shamir.Share]()
            for entry in family["shares"] as! [[String: Any]] {
                let position = entry["index"] as! Int
                let hex = entry["shareHex"] as! String
                var bytes = [UInt8]()
                var cursor = hex.startIndex
                while cursor < hex.endIndex {
                    let next = hex.index(cursor, offsetBy: 2)
                    bytes.append(UInt8(hex[cursor..<next], radix: 16)!)
                    cursor = next
                }
                shares[position] = Shamir.Share(index: UInt8(position), bytes: bytes)
            }

            for subset in family["mustReconstruct"] as! [[Int]] {
                let combined = try Shamir.combine(subset.map { shares[$0]! })
                XCTAssertEqual(combined, secret, "subset \(subset) failed to reconstruct")
            }

            for subset in family["mustNotReconstruct"] as! [[Int]] {
                let combined = try Shamir.combine(subset.map { shares[$0]! })
                XCTAssertNotEqual(combined, secret, "subset \(subset) reconstructed the secret")
            }
        }
    }

    // MARK: - Versions

    func testVersionVectors() throws {
        for family in families(ofKind: "versions") {
            let text = passphrase(family)

            for entry in family["entries"] as! [[String: Any]] {
                let version = entry["version"] as! String
                let blob = try bytes(entry["file"] as! String)

                if entry["mustOpen"] as! Bool {
                    let (plaintext, _) = try Impression.open(blob, using: .passphrase(text))
                    let expected = try bytes(entry["expectedPlaintext"] as! String)
                    XCTAssertEqual(plaintext, expected, "version \(version) did not open")
                } else {
                    XCTAssertThrowsError(try Impression.open(blob, using: .passphrase(text)),
                                         "version \(version) opened and should not have")
                }
            }
        }
    }

    func testForwardMinorVersionIsAccepted() throws {
        let family = families(ofKind: "versions").first!
        let opening = (family["entries"] as! [[String: Any]]).filter {
            ($0["version"] as! String) == "1.9" && ($0["mustOpen"] as! Bool)
        }
        XCTAssertFalse(opening.isEmpty, "no positive forward-minor vector in the corpus")

        for entry in opening {
            let blob = try bytes(entry["file"] as! String)
            let (_, header) = try Impression.open(blob, using: .passphrase(passphrase(family)))
            XCTAssertEqual(header.formatMinor, 9)
        }
    }

    func testPatchedMinorFailsOnTheTagNotTheVersion() throws {
        let family = families(ofKind: "versions").first!
        let entry = (family["entries"] as! [[String: Any]]).first {
            $0["failsOn"] as? String == "authenticationTag"
        }!
        let blob = try bytes(entry["file"] as! String)

        XCTAssertThrowsError(try Impression.open(blob, using: .passphrase(passphrase(family)))) { error in
            guard case ImpressionError.brokenSeal = error else {
                return XCTFail("a legal minor version was refused as \(error)")
            }
        }
    }
}
